# Generated by Django 2.2.16 on 2020-11-23 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_auto_20201123_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 3, 1, 27, 53765, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
