# Generated by Django 2.2.16 on 2020-11-23 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0012_auto_20201123_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 3, 3, 8, 381709, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
