# Generated by Django 2.2.16 on 2020-11-23 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0013_auto_20201123_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 4, 38, 52, 450781, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
