# Generated by Django 2.2.16 on 2020-11-20 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20201120_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 8, 12, 35, 414831, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
