# Generated by Django 2.2.16 on 2020-11-22 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20201122_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 23, 49, 19, 604512, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
