# Generated by Django 2.2.16 on 2020-11-23 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20201122_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 2, 50, 52, 103765, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
