# Generated by Django 2.2.16 on 2020-11-23 03:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0011_auto_20201123_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 3, 2, 39, 805553, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
