# Generated by Django 3.0.8 on 2020-08-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shart_desc',
            new_name='short_desc',
        ),
    ]
